apiVersion: v1
kind: Service
metatdata:
  name: myapp-service
spec:
  type: NodePort
  ports:
  - port: 80 # essential
    targetPort: 80 # 미지정시 port와 동일한 값으로 자동 지정.
    nodePort: 30004 # 미지정시 k8s가 자동 지정
  selector: # 어떤 서비스와 연결할지 레이블로 맵핑
    app: myapp
