version: "3"
services:
  office:
    image: mysql:5.7
    container_name: office
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql/office:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
  db01:
    image: mysql:5.7
    container_name: db01
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql/db01:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    restart: always