version: "3"
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      # MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
    # network_mode: host