apiVersion: networking.k8s.io/v1
# 네트워크 폴리시는 쿠버네티스 클러스터에 구현된 네트워크 솔루션으로 강제 된다, 모든 네트워크 솔루션이 지원하는 것은 아님.
# NetworkPolicy를 지원하는 솔루션: Kube-router, Calico, Romana, Weave-net
# 미지원 솔루션: Flannel
kind: NetworkPolicy
metadata:
  name: db-policy
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    # 1st와 2nd rule은 서로 or 관계이고, 같은 rule 안에서는 and 관계.
    # 1st rule -> api-pod이면서 namespace가 prod인 파드에서의 접근만 허용.
    - podSelector:
        matchLabels:
          name: api-pod
      namespaceSelector:
        matchLabels:
          name: prod
    # 2nd rule -> 특정 ipBlock에서만 접근 가능.
    - ipBlock:
        cidr: 192.168.5.10/32
    ports:
    - protocol: TCP
      port: 3306
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.6.10/32
    ports:
    - protocol: TCP
      port: 80
